### ISSUE TITLE
CLI-1375: getAhFilesRoot() differences with drush and GUI on STAGE environments

### ISSUE THREAD

**Issue by nmillin** [acquia/drupal-environment-detector#95]
This only impacts the STAGE environment. I can work around this, but wanted to let the project know and maybe this will help someone else.

**Describe the bug**
I am using AcquiaDrupalEnvironmentDetector::getAhFilesRoot() to load a secrets file on ACN. It is working via the GUI, but drush commands report a different path.

* GUI -     /mnt/files/[SITE].stage
* Drush - /mnt/files/[SITE].test

**To Reproduce**
Run AcquiaDrupalEnvironmentDetector::getAhFilesRoot() via drush and GUI (echo statement) to see path.

**Expected behavior**
/mnt/files/[SITE].test to be returned since that is the file path I have on Acquia Cloud Next.

**Screenshots**
n/a

**Environment**
n/a

**Additional context**
n/a

**Comment by danepowell** [comment]
Can you provide the output of the following code from both the GUI and Drush?

```php
print getenv('AH_SITE_ENVIRONMENT') . "\n";
print $_ENV['AH_SITE_ENVIRONMENT'] . "\n";
```

You can see that test/stage is coming from the AH_SITE_ENVIRONMENT environment variable, so that must be causing the difference: https://github.com/acquia/drupal-environment-detector/blob/a4c8ec18ebcfb4e0f2fabdade868367dfe695aec/src/AcquiaDrupalEnvironmentDetector.php#L155

**Comment by nmillin** [comment]
Thanks @danepowell for the response. 

print getenv('AH_SITE_ENVIRONMENT') . "\n";
print $_ENV['AH_SITE_ENVIRONMENT'] . "\n";
Provided differences because of the custom code I'm using updating putenv('AH_SITE_ENVIRONMENT=', but not $_ENV. 
I'm going to update my code to not mess with AH_SITE_ENVIRONMENT since that is a bad idea.

Thanks again.
